title: JongWuk Hwang
description: Web Engineer
site_title: 'Wook - Jong Wuk'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: aorri2
blog_url: https://www.nagekar.com
email: aorri96@naver.com
keybase_username: abhn
twitter_username: abhn_
reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
