title: JongWuk Hwang
description: Web Engineer
site_title: 'Wook - Jong Wuk'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: aorri2
blog_url: https://simgee.tistory.com
email: aorri96@naver.com
keybase_username: aorri2
twitter_username: aorri2
reddit_username: aorri2

# absolute or relative
profile_picture: assets/images/profile.jpeg

# Google Analytics ID
google_analytics: 
